### ISSUE TITLE
example does nothing

### ISSUE THREAD

**Issue by BradenWentworth** [SnpM/Lockstep-Framework#70] opened 2016-04-23 13:20 UTC
I followed the instructions on the front page and when I hit play nothing happens, there's no characters to move, no keys or mouse trigger anything at all.
There's just 2 buttons on screen 'Save' and 'Restart' and some white terrain.

Also when i first opened the example scene the 'Manager' object was a broken prefab link.

Using Unity 5.3.4f1

**Comment by nibsbin** [comment] 2016-04-23 17:07
Are there any error messages?

**Comment by BradenWentworth** [comment] 2016-04-24 03:31
nope, but i did discover if you start the game then modify the RTS
controller to have a selection box sprite, it starts to work and you can
move the 2 units around and save and replay actions

**Comment by erebuswolf** [comment] 2016-06-30 09:23
I also have started the example scene and there is really nothing going on. I can't click on anything or do anything. Either it is broken or it needs better instructions.

**Comment by nibsbin** [comment] 2016-06-30 15:11
Interesting. Glad you could find a fix.

**Comment by nibsbin** [comment] 2016-06-30 15:12
In Manager inspector, I think you can tweak how many units are spawned.

**Comment by erebuswolf** [comment] 2016-07-04 18:10
I can spawn 30 units. The problem is the controls. The mouse and keyboard do nothing. I can't select anything.

**Comment by nibsbin** [comment] 2016-07-04 19:18
Didn't you figure out how to move 2 units? Use the same method to move the
30 units.

**Comment by erebuswolf** [comment] 2016-07-04 19:19
No I'm a different guy. I never figured out movement just spawning.

**Comment by nibsbin** [comment] 2016-07-04 20:48
Ah, I see. Replying via email so just thought it was the same person.
There's a missing selection box texture that should be fixed now.

**Comment by erebuswolf** [comment] 2016-07-04 22:55
Thank you!! It works now!

On Mon, Jul 4, 2016 at 1:48 PM, John Pan notifications@github.com wrote:

> Ah, I see. Replying via email so just thought it was the same person.
> There's a missing selection box texture that should be fixed now.
> 
> On Mon, Jul 4, 2016 at 1:19 PM, Jesse Fish notifications@github.com
> wrote:
> 
> > No I'm a different guy. I never figured out movement just spawning.
> > On Jul 4, 2016 1:18 PM, "John Pan" notifications@github.com wrote:
> > 
> > > Didn't you figure out how to move 2 units? Use the same method to move
> > > the
> > > 30 units.
> > > 
> > > On Mon, Jul 4, 2016 at 12:10 PM, Jesse Fish notifications@github.com
> > > wrote:
> > > 
> > > > I can spawn 30 units. The problem is the controls. The mouse and
> > > > keyboard
> > > > do nothing. I can't select anything.
> > > > 
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > 
> > https://github.com/SnpM/LockstepFramework/issues/70#issuecomment-230335952
> > 
> > > > ,
> > > > or mute the thread
> > > > <
> > 
> > https://github.com/notifications/unsubscribe/AHXqp7Z8-O8orXVoxfS8uoUymwVfKPA_ks5qSUyUgaJpZM4IOL46
> > 
> > > > .
> > > 
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > <
> > 
> > https://github.com/SnpM/LockstepFramework/issues/70#issuecomment-230344146
> > 
> > > ,
> > > or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AATf7Odz4gHiVeFOT71C6VHhBIwf-tyuks5qSVybgaJpZM4IOL46
> > 
> > > .
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> > https://github.com/SnpM/LockstepFramework/issues/70#issuecomment-230344252
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AHXqp1knthgXYY0Y4Ghjqx8ALKj5pM_uks5qSVzegaJpZM4IOL46
> > 
> > .
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/SnpM/LockstepFramework/issues/70#issuecomment-230352595,
> or mute the thread
> https://github.com/notifications/unsubscribe/AATf7CYY2JUMMHX6wUu0VTrQwqrmDbKJks5qSXGJgaJpZM4IOL46
> .

## 

Jesse

**Closed as completed** 2016-08-15 04:32 UTC
